on: ['push', 'pull_request']

name: Code Coverage

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 20.x
        uses: actions/setup-node@v1
        with:
          node-version: 20.x

      - name: Install
        run: |
          npm install
          npm run dev:types

      - name: Lint & Test
        run: |
          npm run dev:lint
          npm run dev:test-ci

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
